[workspace]
resolver = "2" # What does this do?

[package]
name = "rui"
description = "Experimental Declarative Rust UI library"
version = "0.1.0"
authors = ["Taylor Holliday <taylor@audulus.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.22.6"
tao = "0.6.3"
wgpu = "0.12.0"
futures = "0.3"
vger = "0.1.0"