[workspace]
resolver = "2" # What does this do?

[package]
name = "rui"
version = "0.1.0"
authors = ["Taylor Holliday <taylor@audulus.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.22.6"
winit = "0.26.0"
vger = { git = "https://github.com/audulus/vger-rs" }