name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Gtk
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev
    - name: Install libappindicator3 (ubuntu[default/tray] only)
      if: matrix.platform.id == 'ubuntu'
      run: |
        sudo apt-get install -y libappindicator3-dev
    - name: Build
      run: cargo build --verbose
